name: Deploy to PyPI

on:
  push:
    branches:
      - master

jobs:
  pypi_deploy:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repo
      - uses: actions/checkout@v2
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}