name: Prod Test - PR

on:
  pull_request:

jobs:
  pytest_build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Create fake logs file
        run: |

          mkdir logs
          cat > logs/example.log
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader vader_lexicon
      - name: Run tests with pytest
        run: pytest -v